-- MySQL Script generated by MySQL Workbench
-- Mon Nov  3 22:30:53 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema CMMCFledgeDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema CMMCFledgeDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `CMMCFledgeDB` DEFAULT CHARACTER SET utf8 ;
USE `CMMCFledgeDB` ;

-- -----------------------------------------------------
-- Table `CMMCFledgeDB`.`CMMC_Controls`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CMMCFledgeDB`.`CMMC_Controls` ;

CREATE TABLE IF NOT EXISTS `CMMCFledgeDB`.`CMMC_Controls` (
  `Control_ID` VARCHAR(10) NOT NULL,
  `Control_Family` VARCHAR(5) NULL,
  `Control_Name` VARCHAR(250) NULL,
  `Control_Explanation` LONGTEXT NULL,
  PRIMARY KEY (`Control_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CMMCFledgeDB`.`Control_Assessments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CMMCFledgeDB`.`Control_Assessments` ;

CREATE TABLE IF NOT EXISTS `CMMCFledgeDB`.`Control_Assessments` (
  `idControl_Assessments` INT NOT NULL,
  `CMMC_Controls_Control_ID` VARCHAR(10) NOT NULL,
  `Assessment_Text` LONGTEXT NULL,
  PRIMARY KEY (`idControl_Assessments`, `CMMC_Controls_Control_ID`),
  INDEX `fk_Control_Assessments_CMMC_Controls1_idx` (`CMMC_Controls_Control_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Control_Assessments_CMMC_Controls1`
    FOREIGN KEY (`CMMC_Controls_Control_ID`)
    REFERENCES `CMMCFledgeDB`.`CMMC_Controls` (`Control_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CMMCFledgeDB`.`CUI_Cat`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CMMCFledgeDB`.`CUI_Cat` ;

CREATE TABLE IF NOT EXISTS `CMMCFledgeDB`.`CUI_Cat` (
  `idCUI_Cat` INT NOT NULL,
  `Cat_Name` VARCHAR(45) NULL,
  `Defense_Index_Group` TINYINT NULL,
  PRIMARY KEY (`idCUI_Cat`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CMMCFledgeDB`.`CUI_Types`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CMMCFledgeDB`.`CUI_Types` ;

CREATE TABLE IF NOT EXISTS `CMMCFledgeDB`.`CUI_Types` (
  `idCUI_Types` INT NOT NULL,
  `CUI_Cat_idCUI_Cat` INT NOT NULL,
  `Type_Name` VARCHAR(200) NULL,
  `Is_Basic` TINYINT NULL,
  PRIMARY KEY (`idCUI_Types`, `CUI_Cat_idCUI_Cat`),
  INDEX `fk_CUI_Types_CUI_Cat1_idx` (`CUI_Cat_idCUI_Cat` ASC) VISIBLE,
  CONSTRAINT `fk_CUI_Types_CUI_Cat1`
    FOREIGN KEY (`CUI_Cat_idCUI_Cat`)
    REFERENCES `CMMCFledgeDB`.`CUI_Cat` (`idCUI_Cat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
